### ISSUE TITLE
iterparse signature differs from lxml iterparse signature

### ISSUE THREAD

**Issue by italomaia** [tiran/defusedxml#13]
defusedxml and lxml iterparse functions have different signatures; shouldn't they accept the same arguments? "tag" argument is quite useful and not available.

**Comment by tiran** [comment]
Thanks for reporting the issue. However the ``defusedxml.lxml`` module was never designed as production code. It's merely an [example](https://github.com/tiran/defusedxml/blob/d0f5633183e7f9f6614814b0d43fb9a18c5ba893/defusedxml/lxml.py#L6) and proof of concept. I have deprecated the module in the upcoming 0.6 release and plan to remove it in 0.7.

Any security issue should be fixed in lxml instead.
