### ISSUE TITLE
lxml module status

### ISSUE THREAD

**Issue by c00kiemon5ter** [tiran/defusedxml#15]
The `defusedxml.lxml` module states that it is [_an example_](https://github.com/tiran/defusedxml/blob/master/defusedxml/lxml.py#L6). What would make this module better?

I see some things around the `lxml` parser that seem to be in question, like whether the `remove_comments` option should be enabled by default, or whether comments should be _blacklisted_. Do you have an opinion on those, especially in relation to [the latest saml vulnerability by duo](https://duo.com/blog/duo-finds-saml-vulnerabilities-affecting-multiple-implementations)?

**Comment by tiran** [comment]
The ``defusedxml.lxml`` module was never designed as production code. As you said it's merely an [example](https://github.com/tiran/defusedxml/blob/d0f5633183e7f9f6614814b0d43fb9a18c5ba893/defusedxml/lxml.py#L6) and proof of concept. I have neither interest, motivation, nor resources to deal with lxml. There I have deprecated the module in the upcoming 0.6 release and plan to remove it in 0.7.

Any security issue should be fixed in lxml instead.
