### ISSUE TITLE
import defusedxml.lxml.html

### ISSUE THREAD

**Issue by spaceone** [tiran/defusedxml#31]
I get an error when trying to use lxml:

```
>>> import defusedxml.lxml.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named html
```

**Comment by tiran** [comment]
Thanks for reporting the issue.

The ``defusedxml.lxml`` module was never designed as production code or fall wrapper around lxml. It's merely an [example](https://github.com/tiran/defusedxml/blob/d0f5633183e7f9f6614814b0d43fb9a18c5ba893/defusedxml/lxml.py#L6) and proof of concept. I have deprecated the module in the upcoming 0.6 release and plan to remove it in 0.7.

Any security issue should be fixed in lxml instead.
